---
rules:
  matrix:
    path: test_data/{{.Item}}/**
    tag: "{{.Item}}-latest"
    tagSuffixFileRef:
      file: test_data/production/{{.Item}}.Deployment.yaml
      regexp: eu.gcr.io/org/proj/{{.Item}}:(.*)$
matrixFromDir: test_data/test_dir
