---
dist: _output
builds:
  - binary: gitlab-tracker
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
